### ISSUE TITLE
SYSTEM.NET.HTTP.HTTPREQUESTEXCEPTION

### ISSUE THREAD

**Issue by phntsm** [aurorabuilder/elements#282]
Upon updating content files for the unearthed arcana index, I get an error message. I'm a new user of the software in general so this is about all of the information I can provide, I apologize if it isn't enough. I will provide the message along with a screenshot. If there is anything further to share, I will do my best. Thank you for your time.

Here is the additional error details from the software ; 

mscorlib

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Builder.Data.Files.ElementsFile.<FromUrl>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Builder.Data.Files.Updater.IndicesUpdateService.<UpdateFileEntries>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Builder.Data.Files.Updater.IndicesUpdateService.<UpdateIndexFiles>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Builder.Presentation.ViewModels.Shell.Start.SourcesSectionViewModel.<UpdateCustomFiles>d__74.MoveNext()

![Screenshot (5)](https://user-images.githubusercontent.com/49613158/56093516-c7670180-5e97-11e9-867b-297b7923cc54.png)

**Comment by phntsm** [comment]
Hmmm... I seem to be having this issue with all of the index files. I added them all in order and then clicked update content files as suggested in the readme. I feel a little foolish, like I must be overlooking something and I apologize for the trouble haha

**Comment by phntsm** [comment]
Okay. In an effort to create a warforged character, after adding the index files originally, and getting the error message, I went to the builder to see if they were added and didn't see it. I then closed the application and tried opening as admin to add them again but still got the error message. However now when I go to the builder, all of the additional information from the index files is present. I'm not sure what the issue is but the content appears to have been downloaded?

**Comment by swdriessen** [comment]
When you click on the 'content folder' button you should see a folder that has the index files downloaded. Also, when the content has been downloaded a number of folders with the same name as the index files. 

You can temporary disable auto-checking for updates in the settings, this way the error won't keep showing up.

Do you see any added content when you create a new character?

**Comment by swdriessen** [comment]
It should work now, there was a typo in some unearthed arcana files that was added yesterday.

**Comment by phntsm** [comment]
Thank you very much! All is working without error now when it updates. I was able to view the added content on new character also, I started my Warforged. Cheers!
