### ISSUE TITLE
cant launch

### ISSUE THREAD

**Issue by fivestargamer** [aurorabuilder/elements#304]
mscorlib

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at Builder.Presentation.Services.Data.DataManager.GetFiles(String directory, String pattern, Boolean includeSubdirectories)
   at Builder.Presentation.Services.Data.DataManager.GetFiles(String directory, String pattern, Boolean includeSubdirectories)
   at Builder.Presentation.Services.Data.DataManager.GetCustomFiles(String path)
   at Builder.Presentation.Services.Data.DataManager.GetCustomFiles()
   at Builder.Presentation.Services.Data.DataManager.<InitializeElementDataAsync>d__75.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Builder.Presentation.ViewModels.LauncherWindowViewModel.<InitializeAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Builder.Presentation.Views.Splash.<MetroWindow_Loaded>d__3.MoveNext()

**Comment by fivestargamer** [comment]
tried uninstalling and reinstalling twice

**Comment by ColdAnkles** [comment]
Try deleting APPDATA/Local/Builder

**Comment by NickVendel** [comment]
@fivestargamer did you fix the issue? If you did, then please close this issue

**Comment by fivestargamer** [comment]
Fixed had to run repair in my ssd
